In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [15]:
b = np.array([[[1,1],[2,1],[3,1]],[[4,1],[5,1],[6,1]]])
print(b)

[[[1 1]
  [2 1]
  [3 1]]

 [[4 1]
  [5 1]
  [6 1]]]


In [16]:
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

(2, 3, 2)
[1 1] [2 1] [4 1]


In [18]:
a = np.zeros((2,3,2))
print(a)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [20]:
b = np.ones((1,2),dtype=int)
print(b)

[[1 1]]


In [21]:
c = np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [22]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [23]:
e = np.random.random((2,2))
print(e)

[[0.72825343 0.32463235]
 [0.997999   0.50351043]]


In [25]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[1,2])

b = a[:2,1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[[2 3]
 [6 7]]


In [27]:
h = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(h)
i = h[:2,1:3]
print(h[0,1])
i[0,0] = 77
print(h[0,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
77


In [30]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
bool_idx = (a>2)
print(bool_idx)
print(bool_idx.dtype) # datatype of elements -> boolean value
print(type(bool_idx)) # datatype of matrix -> numpy array

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
bool
<class 'numpy.ndarray'>


In [29]:
print(a[bool_idx])
print(a[a>2])

[3 4 5 6]
[3 4 5 6]
